name = input("what's your name?\n")
print(f"Welcome on board {name}!")
city = input("What city did you grow up in?\n")
pet = input("What's the name of your pet?\n")
print(f"Your band name is {city} {pet}!")
